default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV.fetch("RECIPES_DATABASE_HOST") { "localhost" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= ENV["RECIPES_PASSWORD"] %>
development:
  <<: *default
  database: recipes_development
  username: root
test:
  <<: *default
  database: recipes_test
  username: root
production:
  <<: *default
  database: recipes_production
  username: recipes_production
staging:
  <<: *default
  database: recipes_staging
  username: recipes_staging
